Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--rhd2d--resnet_rhd2d [SimpleBaseline2D+ResNet@RHD]
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/resnet_rhd2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/res50_rhd2d_256x256.py
  In Collection: hand--2d_kpt_sview_rgb_img--topdown_heatmap--rhd2d--resnet_rhd2d
    [SimpleBaseline2D+ResNet@RHD]
  Metadata:
    Training Data: RHD
  Name: topdown_heatmap_res50_rhd2d_256x256
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.898
      EPE: 2.33
      PCK@0.2: 0.991
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_rhd2d_256x256-5dc7e4cc_20210330.pth
