Collections:
- Metadata:
    Architecture:
    - CPM
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--cpm_mpii [CPM@MPII]
  Paper:
    Title: Convolutional pose machines
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/Wei_Convolutional_Pose_Machines_CVPR_2016_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/cpm_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/cpm_mpii_368x368.py
  In Collection: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--cpm_mpii [CPM@MPII]
  Metadata:
    Training Data: MPII
  Name: topdown_heatmap_cpm_mpii_368x368
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.876
      Mean@0.1: 0.285
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_mpii_368x368-116e62b8_20200822.pth
