Collections:
- Metadata:
    Architecture:
    - HRNet
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--hrnet_mpii [HRNet@MPII]
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_w32_mpii_256x256.py
  In Collection: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--hrnet_mpii [HRNet@MPII]
  Metadata:
    Training Data: MPII
  Name: topdown_heatmap_hrnet_w32_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.9
      Mean@0.1: 0.334
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_mpii_256x256-6c4f923f_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hrnet_w48_mpii_256x256.py
  In Collection: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--hrnet_mpii [HRNet@MPII]
  Metadata:
    Training Data: MPII
  Name: topdown_heatmap_hrnet_w48_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.901
      Mean@0.1: 0.337
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_mpii_256x256-92cab7bd_20200812.pth
