Collections:
- Metadata:
    Architecture:
    - MobilenetV2
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--mobilenetv2_mpii [MobilenetV2@MPII]
  Paper:
    Title: 'Mobilenetv2: Inverted residuals and linear bottlenecks'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/mobilenetv2_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mobilenet_v2/mpii/mobilenet_v2_mpii_256x256.py
  In Collection: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--mobilenetv2_mpii
    [MobilenetV2@MPII]
  Metadata:
    Training Data: MPII
  Name: topdown_heatmap_mpii
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.854
      Mean@0.1: 0.235
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/mobilenetv2/mobilenetv2_mpii_256x256-e068afa7_20200812.pth
