Collections:
- Metadata:
    Architecture:
    - ResNext
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--resnext_mpii [ResNext@MPII]
  Paper:
    Title: Aggregated residual transformations for deep neural networks
    URL: http://openaccess.thecvf.com/content_cvpr_2017/html/Xie_Aggregated_Residual_Transformations_CVPR_2017_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnext_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnext152_mpii_256x256.py
  In Collection: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--resnext_mpii [ResNext@MPII]
  Metadata:
    Training Data: MPII
  Name: topdown_heatmap_resnext152_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.887
      Mean@0.1: 0.294
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnext/resnext152_mpii_256x256-df302719_20200927.pth
