Collections:
- Metadata:
    Architecture:
    - ShufflenetV1
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--shufflenetv1_mpii [ShufflenetV1@MPII]
  Paper:
    Title: 'Shufflenet: An extremely efficient convolutional neural network for mobile
      devices'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Zhang_ShuffleNet_An_Extremely_CVPR_2018_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv1_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv1_mpii_256x256.py
  In Collection: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--shufflenetv1_mpii
    [ShufflenetV1@MPII]
  Metadata:
    Training Data: MPII
  Name: topdown_heatmap_shufflenetv1_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.823
      Mean@0.1: 0.195
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv1/shufflenetv1_mpii_256x256-dcc1c896_20200925.pth
