Collections:
- Metadata:
    Architecture:
    - HMR
    - ResNet
  Name: body--3d_mesh_sview_rgb_img--hmr--mixed--resnet_mixed [HMR+ResNet@Human3.6M]
  Paper:
    Title: End-to-end Recovery of Human Shape and Pose
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Kanazawa_End-to-End_Recovery_of_CVPR_2018_paper.html
  README: configs/body/3d_mesh_sview_rgb_img/hmr/mixed/resnet_mixed.md
Models:
- Config: configs/body/3d_mesh_sview_rgb_img/hmr/mixed/res50_mixed_224x224.py
  In Collection: body--3d_mesh_sview_rgb_img--hmr--mixed--resnet_mixed [HMR+ResNet@Human3.6M]
  Metadata:
    Training Data: Human3.6M
  Name: hmr_res50_mixed_224x224
  Results:
  - Dataset: Human3.6M
    Metrics:
      MPJPE (P1): 80.75
      MPJPE (P2): 80.35
      MPJPE-PA (P1): 55.08
      MPJPE-PA (P2): 52.6
    Task: Body 3D Mesh
  Weights: https://download.openmmlab.com/mmpose/mesh/hmr/hmr_mesh_224x224-c21e8229_20201015.pth
