Collections:
- Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_hand--hrnetv2_dark_coco_wholebody_hand
    [HRNetv2+DarkPose@COCO-WholeBody-Hand]
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/hrnetv2_dark_coco_wholebody_hand.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/hrnetv2_w18_coco_wholebody_hand_256x256_dark.py
  In Collection: hand--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_hand--hrnetv2_dark_coco_wholebody_hand
    [HRNetv2+DarkPose@COCO-WholeBody-Hand]
  Metadata:
    Training Data: COCO-WholeBody-Hand
  Name: topdown_heatmap_hrnetv2_w18_coco_wholebody_hand_256x256_dark
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.84
      EPE: 4.37
      PCK@0.2: 0.814
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/dark/hrnetv2_w18_coco_wholebody_hand_256x256_dark-a9228c9c_20210908.pth
