Collections:
- Metadata:
    Architecture:
    - LiteHRNet
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_hand--litehrnet_coco_wholebody_hand
    [LiteHRNet@COCO-WholeBody-Hand]
  Paper:
    Title: 'Lite-HRNet: A Lightweight High-Resolution Network'
    URL: https://arxiv.org/abs/2104.06403
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/litehrnet_coco_wholebody_hand.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/litehrnet_w18_coco_wholebody_hand_256x256.py
  In Collection: hand--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_hand--litehrnet_coco_wholebody_hand
    [LiteHRNet@COCO-WholeBody-Hand]
  Metadata:
    Training Data: COCO-WholeBody-Hand
  Name: topdown_heatmap_litehrnet_w18_coco_wholebody_hand_256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.83
      EPE: 4.77
      PCK@0.2: 0.795
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/litehrnet/litehrnet_w18_coco_wholebody_hand_256x256-d6945e6a_20210908.pth
