Collections:
- Metadata:
    Architecture:
    - HRNet
    - DarkPose
  Name: wholebody--2d_kpt_sview_rgb_img--topdown_heatmap--halpe--hrnet_dark_halpe
    [HRNet+DarkPose@Halpe]
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/halpe/hrnet_dark_halpe.md
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/halpe/hrnet_w48_halpe_384x288_dark_plus.py
  In Collection: wholebody--2d_kpt_sview_rgb_img--topdown_heatmap--halpe--hrnet_dark_halpe
    [HRNet+DarkPose@Halpe]
  Metadata:
    Training Data: Halpe
  Name: topdown_heatmap_hrnet_w48_halpe_384x288_dark_plus
  Results:
  - Dataset: Halpe
    Metrics:
      Whole AP: 0.531
      Whole AR: 0.642
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_halpe_384x288_dark_plus-d13c2588_20211021.pth
