Collections:
- Metadata:
    Architecture:
    - HRNetv2
  Name: face--2d_kpt_sview_rgb_img--topdown_heatmap--wflw--hrnetv2_wflw [HRNetv2@WFLW]
  Paper:
    Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_wflw.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_w18_wflw_256x256.py
  In Collection: face--2d_kpt_sview_rgb_img--topdown_heatmap--wflw--hrnetv2_wflw [HRNetv2@WFLW]
  Metadata:
    Training Data: WFLW
  Name: topdown_heatmap_hrnetv2_w18_wflw_256x256
  Results:
  - Dataset: WFLW
    Metrics:
      NME blur: 4.59
      NME expression: 4.33
      NME illumination: 3.99
      NME makeup: 3.92
      NME occlusion: 4.83
      NME pose: 6.98
      NME test: 4.06
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_wflw_256x256-2bf032a6_20210125.pth
