Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: fashion--2d_kpt_sview_rgb_img--topdown_heatmap--deepfashion--resnet_deepfashion
    [SimpleBaseline2D+ResNet@DeepFashion]
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/resnet_deepfashion.md
Models:
- Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_upper_256x192.py
  In Collection: fashion--2d_kpt_sview_rgb_img--topdown_heatmap--deepfashion--resnet_deepfashion
    [SimpleBaseline2D+ResNet@DeepFashion]
  Metadata:
    Training Data: DeepFashion
  Name: topdown_heatmap_res50_deepfashion_upper_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.578
      EPE: 16.8
      PCK@0.2: 0.954
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_upper_256x192-41794f03_20210124.pth
- Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_lower_256x192.py
  In Collection: fashion--2d_kpt_sview_rgb_img--topdown_heatmap--deepfashion--resnet_deepfashion
    [SimpleBaseline2D+ResNet@DeepFashion]
  Metadata:
    Training Data: DeepFashion
  Name: topdown_heatmap_res50_deepfashion_lower_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.744
      EPE: 10.5
      PCK@0.2: 0.965
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_lower_256x192-1292a839_20210124.pth
- Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_full_256x192.py
  In Collection: fashion--2d_kpt_sview_rgb_img--topdown_heatmap--deepfashion--resnet_deepfashion
    [SimpleBaseline2D+ResNet@DeepFashion]
  Metadata:
    Training Data: DeepFashion
  Name: topdown_heatmap_res50_deepfashion_full_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.664
      EPE: 12.7
      PCK@0.2: 0.977
    Task: Fashion 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_full_256x192-0dbd6e42_20210124.pth
