Collections:
- Metadata:
    Architecture:
    - SimpleBaseline3D
  Name: body--3d_kpt_sview_rgb_img--pose_lift--mpi_inf_3dhp--simplebaseline3d_mpi-inf-3dhp
    [SimpleBaseline3D@MPI-INF-3DHP]
  Paper:
    Title: A simple yet effective baseline for 3d human pose estimation
    URL: http://openaccess.thecvf.com/content_iccv_2017/html/Martinez_A_Simple_yet_ICCV_2017_paper.html
  README: configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.md
Models:
- Config: configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.py
  In Collection: body--3d_kpt_sview_rgb_img--pose_lift--mpi_inf_3dhp--simplebaseline3d_mpi-inf-3dhp
    [SimpleBaseline3D@MPI-INF-3DHP]
  Metadata:
    Training Data: MPI-INF-3DHP
  Name: pose_lift_simplebaseline3d_mpi-inf-3dhp
  Results:
  - Dataset: MPI-INF-3DHP
    Metrics:
      3DAUC: 52.0
      3DPCK: 85.0
      MPJPE: 84.3
      P-MPJPE: 53.2
    Task: Body 3D Keypoint
  Weights: https://download.openmmlab.com/mmpose/body3d/simplebaseline3d/simplebaseline3d_mpi-inf-3dhp-b75546f6_20210603.pth
