Collections:
- Metadata:
    Architecture:
    - HRNetv2
  Name: face--2d_kpt_sview_rgb_img--topdown_heatmap--300w--hrnetv2_300w [HRNetv2@300W]
  Paper:
    Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/300w/hrnetv2_300w.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/300w/hrnetv2_w18_300w_256x256.py
  In Collection: face--2d_kpt_sview_rgb_img--topdown_heatmap--300w--hrnetv2_300w [HRNetv2@300W]
  Metadata:
    Training Data: 300W
  Name: topdown_heatmap_hrnetv2_w18_300w_256x256
  Results:
  - Dataset: 300W
    Metrics:
      NME challenge: 5.45
      NME common: 2.86
      NME full: 3.37
      NME test: 3.97
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_300w_256x256-eea53406_20211019.pth
