Collections:
- Metadata:
    Architecture:
    - DeepPose
    - ResNet
  Name: hand--2d_kpt_sview_rgb_img--deeppose--panoptic2d--resnet_panoptic2d [DeepPose+ResNet@CMU
    Panoptic HandDB]
  Paper:
    Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/deeppose/panoptic2d/resnet_panoptic2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/deeppose/panoptic2d/res50_panoptic2d_256x256.py
  In Collection: hand--2d_kpt_sview_rgb_img--deeppose--panoptic2d--resnet_panoptic2d
    [DeepPose+ResNet@CMU Panoptic HandDB]
  Metadata:
    Training Data: CMU Panoptic HandDB
  Name: deeppose_res50_panoptic2d_256x256
  Results:
  - Dataset: CMU Panoptic HandDB
    Metrics:
      AUC: 0.686
      EPE: 9.36
      PCKh@0.7: 0.999
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/deeppose/deeppose_res50_panoptic_256x256-8a745183_20210330.pth
