Collections:
- Metadata:
    Architecture:
    - HRNet
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--ap10k--hrnet_ap10k [HRNet@AP-10K]
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/hrnet_ap10k.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/hrnet_w32_ap10k_256x256.py
  In Collection: animal--2d_kpt_sview_rgb_img--topdown_heatmap--ap10k--hrnet_ap10k
    [HRNet@AP-10K]
  Metadata:
    Training Data: AP-10K
  Name: topdown_heatmap_hrnet_w32_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.738
      AP@0.5: 0.958
      AP@0.75: 0.808
      APL: 0.743
      APM: 0.592
    Task: Animal 2D Keypoint
  Weights: ''
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/hrnet_w48_ap10k_256x256.py
  In Collection: animal--2d_kpt_sview_rgb_img--topdown_heatmap--ap10k--hrnet_ap10k
    [HRNet@AP-10K]
  Metadata:
    Training Data: AP-10K
  Name: topdown_heatmap_hrnet_w48_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.744
      AP@0.5: 0.959
      AP@0.75: 0.807
      APL: 0.748
      APM: 0.589
    Task: Animal 2D Keypoint
  Weights: ''
