Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--fly--resnet_fly [SimpleBaseline2D@Vinegar
    Fly]
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/resnet_fly.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res50_fly_192x192.py
  In Collection: animal--2d_kpt_sview_rgb_img--topdown_heatmap--fly--resnet_fly [SimpleBaseline2D@Vinegar
    Fly]
  Metadata:
    Training Data: Vinegar Fly
  Name: topdown_heatmap_res50_fly_192x192
  Results:
  - Dataset: Vinegar Fly
    Metrics:
      AUC: 0.91
      EPE: 2.0
      PCK@0.2: 0.996
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_fly_192x192-5d0ee2d9_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res101_fly_192x192.py
  In Collection: animal--2d_kpt_sview_rgb_img--topdown_heatmap--fly--resnet_fly [SimpleBaseline2D@Vinegar
    Fly]
  Metadata:
    Training Data: Vinegar Fly
  Name: topdown_heatmap_res101_fly_192x192
  Results:
  - Dataset: Vinegar Fly
    Metrics:
      AUC: 0.912
      EPE: 1.95
      PCK@0.2: 0.996
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_fly_192x192-41a7a6cc_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res152_fly_192x192.py
  In Collection: animal--2d_kpt_sview_rgb_img--topdown_heatmap--fly--resnet_fly [SimpleBaseline2D@Vinegar
    Fly]
  Metadata:
    Training Data: Vinegar Fly
  Name: topdown_heatmap_res152_fly_192x192
  Results:
  - Dataset: Vinegar Fly
    Metrics:
      AUC: 0.917
      EPE: 1.78
      PCK@0.2: 0.997
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_fly_192x192-fcafbd5a_20210407.pth
