Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--resnet_fp16_coco [SimpleBaseline2D+ResNet@COCO]
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnet_fp16_coco.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192_fp16_dynamic.py
  In Collection: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--resnet_fp16_coco
    [SimpleBaseline2D+ResNet@COCO]
  Metadata:
    Training Data: COCO
  Name: topdown_heatmap_res50_coco_256x192_fp16_dynamic
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.717
      AP@0.5: 0.898
      AP@0.75: 0.793
      AR: 0.772
      AR@0.5: 0.936
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192_fp16_dynamic-6edb79f3_20210430.pth
