Collections:
- Metadata:
    Architecture:
    - MobilenetV2
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--panoptic2d--mobilenetv2_panoptic2d
    [MobilenetV2@CMU Panoptic HandDB]
  Paper:
    Title: 'Mobilenetv2: Inverted residuals and linear bottlenecks'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/mobilenetv2_panoptic2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/mobilenetv2_panoptic_256x256.py
  In Collection: hand--2d_kpt_sview_rgb_img--topdown_heatmap--panoptic2d--mobilenetv2_panoptic2d
    [MobilenetV2@CMU Panoptic HandDB]
  Metadata:
    Training Data: CMU Panoptic HandDB
  Name: topdown_heatmap_mobilenetv2_panoptic_256x256
  Results:
  - Dataset: CMU Panoptic HandDB
    Metrics:
      AUC: 0.694
      EPE: 9.7
      PCKh@0.7: 0.998
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_panoptic_256x256-b733d98c_20210330.pth
